---
title: "Clase de R"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---
#Diseños experimentales
##DCA: Diseño completamente al azar
Dosis (4) de fertilización nitrogenada:
-0
-50
-100
-150

Reps: 5
```{r}
# Instalar y cargar el paquete agricolae
#install.packages("agricolae")
library(agricolae)


# Definir los tratamientos (dosis de fertilización nitrogenada)
trt <- c(0, 50, 100, 150)

# Definir el número de repeticiones
#repeticiones <- 5

# Generar el diseño completamente al azar (DCA)
dca <- design.crd(trt = trt, 5, seed=123)

# Mostrar el diseño completo
print(dca)



##DBCA
#Factor 1 (dosis nitrogeno):0,50,100,150
#Factor 2 (variedades de papa):canchan y peruanita
#Bloques: 5

```

```{r}
dosis <-c(0,50,100,150)
Variedad <-c("canchan","peruanita")
#ds <- agricolae::design.ab()

trt<-c(4,2) # factorial 4x2
outdesign <-design.ab(trt = trt, r=5)
str(outdesign)

book<-outdesign$book
book
```


```{r}
library(readxl)
fb <- read_excel("LA MOLINA 2014 POTATO WUE (FB).xlsx", 
    sheet = "fb")


```{r}
str(fb)
modelo <-aov(formula = lfa~bloque+riego+geno+riego*geno,data = fb)

plot(modelo)

anova(modelo)

##comparación de medias
```

```{r}
library(agricolae)
mc <-agricolae::duncan.test(y = modelo,trt = c("riego","geno"))

mc


str(mc)
```

```{r}
library(emmeans)
library(multcomp)
library(tidyverse)

mc<- emmeans(modelo, ~ riego | geno) %>%
  cld(letters = letters, reversed =T)

mc
##grafico
```

```{r}
library(inti)
plot_smr(data = mc
         , type = "bar"
         , x = "geno"
         , y = "emmean"
         , group = "riego"
         , sig = ".group"
         , error = "SE"
         , ylimits = c(0, 12000, 2000)
         )
```

